node
{
    stage('SCM  Checkout'){
        git 'https://github.com/harsha-299/FirstMavenTest'
    }
    stage('compile package')
    {
        def mvnHome= tool name: 'apache-maven', type: 'maven'
        sh "${mvnHome}/bin/mvn package"
    }
}
        
